# Netlify Configuration for Hidden Profit Finder™
[build]
  # No build process needed - static HTML site
  publish = "."

[build.environment]
  # Environment settings for production
  NODE_VERSION = "18"

# Performance and security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

    # HTTPS redirect
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache optimization for assets
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=86400"  # 24 hours for HTML

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling for lead capture
[forms]
  # This enables Netlify's built-in form handling

# Analytics and performance monitoring
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Environment-specific settings
[context.production]
  environment = { NODE_ENV = "production" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Functions configuration (for future enhancements)
[functions]
  directory = "netlify/functions"
